---
Author: HARSHITHA YEDDULA
output: Assignment-5/Query Databases and Dataframes in R with SQL 
---


```{r}

library(RSQLite)

fpath = "C:/DBMS/SQL/Databases/"
dbfile = "MediaDB.db"

# if database file already exists, we connect to it, otherwise
# we create a new database

dbcon <- dbConnect(RSQLite::SQLite(), paste0(fpath,dbfile))

```

#Question-1
```{r}
sqlCmd = "SELECT * FROM invoice_items"
rs = dbGetQuery(dbcon, sqlCmd)
rs
rs$ExtPrice = rs$UnitPrice * rs$Quantity
round(mean(rs$ExtPrice),2)
```


#Question - 2
```{r}
rs2 <- sqldf("SELECT InvoiceId, sum(ExtPrice) as TotalAmount, count(InvoiceLineId) 
as NumberOfItems  FROM rs GROUP BY InvoiceId")
rs2
```

#Qquestion - 3
```{r}
plot(x=rs2$Number,rs2$Total, xlab ="Number of Items", ylab ="Total")
```

#Question - 4
```{r}
library(sqldf)

sqlCmd = "SELECT * FROM invoice_items"


rs = dbGetQuery(dbcon, sqlCmd)
rs$ExtPrice = rs$UnitPrice * rs$Quantity

rs1 <- sqldf("SELECT InvoiceId, sum(ExtPrice) as Total, count(InvoiceLineId) 
as Number  FROM rs GROUP BY InvoiceId")

rs2 <- sqldf(c("UPDATE rs1 SET Total = Total*0.9 
WHERE Number > 5","SELECT * from rs1")) 

rs2 <- sqldf(c("ALTER TABLE rs2 RENAME COLUMN Total TO DiscPrice",
               "SELECT * FROM rs2"))

```

#Question - 5

```{r}
head(rs2,15)
```


```{r}
dbDisconnect(dbcon)
```





